### ISSUE TITLE
建议不要把package依赖包放在repository里面

### ISSUE THREAD

**Issue by ridethepig** [Jie2GG/Native.Cqp.Csharp#39]
GitHub速度不稳定，把依赖包放在里面会导致clone速度大幅度下降，严重影响体验。建议在gitignore中添加/package。谢谢

**Comment by chenxuuu** [comment]
同意楼上

删掉历史纪录里所有的package吧，然后force push

**Comment by Jie2GG** [comment]
删除 package 会导致 Nuget 包还原不准确, 会影响 SDK 核心功能的正常运行. 建议还是耐心下载. 感谢对 SDK 的支持 !

**Comment by Jie2GG** [comment]
> GitHub速度不稳定，把依赖包放在里面会导致克隆速度大幅度下降，严重影响体验。建议在gitignore中添加/Package谢谢

删除包会导致Nuget包还原不准确，会影响SDK核心功能的正常运行。建议还是耐心下载.感谢对SDK的支持！

**Comment by ridethepig** [comment]
尊重作者决定。
谢谢

**Comment by Jie2GG** [comment]
> 尊重作者决定。
> 谢谢

感谢你的支持, 因为之前传 github 的时候, 就是没有传相关的依赖项, 导致 SDK 直接就不可用了. 也无法修复. 很抱歉给你带来了不便
